- hosts: server 
  become: true
  tasks:
    - name: copy server 1 to server 2
      ansible.builtin.copy:
        src: "/var/jenkins_home/workspace/Petclinic 2/target/spring-petclinic-3.0.0-SNAPSHOT.jar"
        dest: "/tmp/spring-petclinic-3.0.0-SNAPSHOT.jar"
    - name: launch petclinic
      command: "java -jar /tmp/spring-petclinic-3.0.0-SNAPSHOT.jar"